<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Dropdown Content</description>
   <name>dropdown_content</name>
   <tag></tag>
   <elementGuidId>f11eb489-5e24-4555-a8ae-c1ab530aed49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;type&quot;]</value>
   </webElementProperties>
</WebElementEntity>
